DROP TABLE IF EXISTS USERS CASCADE;
CREATE TABLE USERS
(
    USER_ID   BIGINT                NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_NAME CHARACTER VARYING(45),
    EMAIL     CHARACTER VARYING(45) NOT NULL,
    UNIQUE (EMAIL)
);

DROP TABLE IF EXISTS ITEMS CASCADE;
CREATE TABLE ITEMS
(
    ITEM_ID          BIGINT                 NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ITEM_NAME        CHARACTER VARYING(45)  NOT NULL,
    ITEM_DESCRIPTION CHARACTER VARYING(200) NOT NULL,
    AVAILABLE        BOOLEAN,
    OWNER_ID         BIGINT                 NOT NULL REFERENCES USERS (USER_ID),
    REQUEST_ID       BIGINT
);
